version: "3.1"

services:
  web:
    environment:
      FLASK_ENV: development
      TESTING: 1
      DATABASE_URI: "mongodb://diary:diary@db:27017"
    restart: always
    build: .
    image: school-diary:dev
    working_dir: /app
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - schoolydiary
  db:
    image: mongo:4.4.5-bionic
    ports:
      - '27017:27017'
    volumes:
      - /tmp/.mongo.db:/data/db
    environment:
      MONGO_REPLICA_SET_NAME: diary
      MONGO_INITDB_DATABASE: diary
      MONGO_INITDB_ROOT_USERNAME: diary
      MONGO_INITDB_ROOT_PASSWORD: diary
    networks:
      - schoolydiary
    depends_on:
      - web
networks:
  schoolydiary:
    driver: bridge
