version: "3.1"

services:
  school-diary:
    restart: always
    environment:
      PORT: 3000
      MONGO_URL: mongodb://schoolydiary:schoolydiary@mongo:27017
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: school-diary:dev
    working_dir: /app
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - schoolydiary
  mongo:
    image: mongo:4.4.5-bionic
    ports:
      - '27017:27017'
    volumes:
      - ./.mongo.db:/data/db
    environment:
      MONGO_REPLICA_SET_NAME: schoolydiary
      MONGO_INITDB_DATABASE: schoolydiary
      MONGO_INITDB_ROOT_USERNAME: schoolydiary
      MONGO_INITDB_ROOT_PASSWORD: schoolydiary
    networks:
      - schoolydiary
networks:
  schoolydiary:
    driver: bridge
